### ISSUE TITLE
Priest Racial Spells Quests

### ISSUE THREAD

**Issue by Mibu86** [CoronaCore/Issues#26] opened 2014-06-04 15:17 UTC
most of them r broken because the target npc guard cannot be healed or ..etc..missing npc flags etc.. i will edit later on wen i get time for detail...
M just pinpointing since i know we had few words about it a long time ago and u said all Priest racial quests r working..well they r not..just test the human Quest...and even if u use GM complete command..wen u turn it back u still dont get rank 1 of the appropriate spells

(Mangos one)

**Comment by Salja** [comment] 2014-06-04 16:43
What quest id ?

**Comment by Mibu86** [comment] 2014-06-05 05:11
This is just the Human priest quest version..

5624 Garments of light 
Issue :100: 
1: ..there is smth Strange with Guard Roberts ..check his Flag..change it..kill him respawn him check again..u can target him but u cant heal him or buff him.
2. complete the quest with .quest complete command...turn it back..u dont get rank 1 of ure Priest racial skills

Personal idea...the db was made from a newer db and all Priest racial spells that were gifted at the turn back of completed quest are removed and need to be readded.(just saying)

**Comment by Mibu86** [comment] 2014-06-13 08:41
momentarily because all the other racial spells for priests can be found from rank 2 and up at the trainer m using this .lua script some guys helped me with some time ago...
(just saying in case u wanna add it to ure .lua script as a temporally fix)

![untitled](https://cloud.githubusercontent.com/assets/6356589/3268047/e6262952-f2d6-11e3-937e-2d7321d898fe.jpg)
actually ure one of the guys who helped me :))
here:
http://emudevs.com/showthread.php/2207-Priest-Racial-spells-autolearn?p=14956#post14956

**Comment by Salja** [comment] 2014-06-13 08:47
Im sure i have a core fix for it i hope i becomd my pc fast back from apple xd

**Comment by Mibu86** [comment] 2014-06-13 08:52
well wen u get you're pc ure going to have a huge bug list here :))

**Comment by Salja** [comment] 2014-06-13 09:01
I see xd but is not a problem xd

**Comment by Salja** [comment] 2014-06-16 10:34
Here test this http://paste2.org/a3P0f0IZ

**Comment by Mibu86** [comment] 2014-06-16 21:14
u need to tell me the lines..pos...were to paste that in the cpp so i wont fuck it up

**Comment by Salja** [comment] 2014-06-16 21:26
This is a patch file you can patch in your source with git bash patch -p1 < name.patch but wehn you have easyer to add manuel than here https://github.com/CoronaCore/OneServer/blob/develop/src/game/Creature.cpp#L392

**Comment by Salja** [comment] 2014-06-20 21:26
you test it ?

**Comment by Salja** [comment] 2014-06-30 17:03
?????????

**Comment by Mibu86** [comment] 2014-06-30 21:23
nope because i didint knew how to apply the patch..and it's not a patch is just a code...how can i make this a patch?

**Comment by Mibu86** [comment] 2014-07-02 03:06
just link me the fkking .diff file (working one)  my programing skills suck!  and that site of yours suck's balls! every time i try to copy that shit it comes out totally messed up and i dont know how to rearrange it! and my notepad ++ dosent make .patch it makes .diff ..
Whatever if u can link me a working patch or diff  ok'e but no more code like that it just pissed me of for the last 30 min.

**Comment by Mibu86** [comment] 2014-10-17 10:41
Still not fixxed.
Priest issues must be fixxed...
Here Human version test:
![wowscrnshot_101714_133841](https://cloud.githubusercontent.com/assets/6356589/4677600/fbfc8dae-55e9-11e4-8cea-d11b51393b8a.jpg)
went to the guy with quest...cant heal or fortify him...it casts on caster not on target..
Teached myself rank 1...went to priest trainer...the other rank's are missing 
:|

**Comment by Salja** [comment] 2014-10-17 11:09
You teast it with the patch or not ?

**Comment by Mibu86** [comment] 2014-10-17 11:48
without patch...

**Comment by Salja** [comment] 2014-10-17 11:55
with patch must work i will test it today

**Comment by Mibu86** [comment] 2014-10-17 12:25
maybe..but will the patch fix the missing rank's for those spells? because the priest trainer lack's them

**Comment by Mibu86** [comment] 2014-10-17 17:21
can u arrange that patch for me..? i mean in line...so i can actually patch with it..m not good at this.

**Comment by Mibu86** [comment] 2014-10-18 18:37
can you arrange the patch in a .diff file and link it back here..i fail at that

**Comment by Salja** [comment] 2014-10-18 18:46
Not at home today but look on paste thats just one line to copy and past in the file what im link

**Comment by Salja** [comment] 2014-10-18 18:46
Or i push monday in repo

**Comment by ghost** [comment] 2014-10-19 00:50
Forgive me for being pedantic, but shouldn't the title be 'Priest **Class** Spells Quests' instead of "Priest Racial Spells Quests"? :smirk:

**Comment by Mibu86** [comment] 2014-10-19 03:58
:| is there a diference?

**Comment by Salja** [comment] 2014-10-19 07:03
Race is as example nightelf, gnome, bloodelf, human etc and class is priest, paladin, shaman etc

**Comment by Mibu86** [comment] 2014-10-22 21:44
I reminded something...right now...the problem is handled by that lua script that gives rank 1 to all priest players at lvl 8..but..    The other ranks of those spells seem to be missing from the priest trainer.
Either way..with a fix on those quests or not...the priest trainer must be fixed

**Comment by Salja** [comment] 2014-10-22 21:50
I check it tomorrow 99%

**Comment by Salja** [comment] 2014-10-23 15:00
hmm i check it atm not really idea must be more look on weekend of it move to my first todo list

**Comment by Mibu86** [comment] 2014-10-23 18:03
wut do you mean "i check it atm ..no idea?" are the spells missing from trainer or not?

**Comment by Salja** [comment] 2014-10-23 18:08
I mean not the spells i mean the traget bug about the quest about the spells i will look later on day

**Comment by Salja** [comment] 2014-11-02 17:18
now quest is fixed BUT not understand you second problem wehn you complete the quest you become a item not a spell but you talk about spells i cant understand

**Comment by Mibu86** [comment] 2014-11-03 10:36
Yes when u complete the quest u receive an item as a reward "a robe" but also the second u complete u also get rank 1 of ure racial priest spell ...and the other rank's u train yourself from the priest trainer.
I know the quest dosent say anything about it ...but if u look for the rank 1 of those racial spells u will see they are quest rewards (kinda hard to find the info atm i see with the new patches wowhead lost that info)

Spell info got deleted from Wowhead here it should be the human rank 1 Feedback spell:
http://www.wowhead.com/spell=6347
U can see here that is Quest reward Here and find some info about these spells m talking about :
http://www.wowhead.com/quest=5650/garments-of-darkness
here u can find this comment :

"cloudp on 2008/12/05 (Patch 3.0.3)"
"This is a reference to Devouring Plague, a racial spell that Undead priests once possessed as exclusive. Humans and Dwarves had Desperate Prayer, Draenei had Symbol of Hope, Night Elves had Elune's Grace and Starshards, Undead had Devouring Plague, Trolls had Shadowguard and Blood Elves had Consume Magic. It is now (in Wrath) obsolete. Guarments of Darkness gives us an explanation lore-wise for the use of the Holy element by the Forsaken Priests, a force they see as convinient: "not your only role. You have acknowledged that there is merit in knowing the healing arts." This is a very importa"

All the spells rank 1 listed above should be rewarded by this quest on completion ..+ the robe reward.Check and u will see all Priests nomatter the race have a simillar "Garments quest" just named a lil different "of light-of darkness" etc.

**Comment by Mibu86** [comment] 2014-11-03 10:40
u need to find some 2.4.3 database that holds the corect info of these spells ...seems to be  Lastwow db lack's the info 2

**Comment by Mibu86** [comment] 2014-11-03 11:01
i will need you to push this fix to AIO branch so i can test it

**Comment by Salja** [comment] 2014-11-03 11:07
The fix is in scripts not core

**Comment by Salja** [comment] 2014-11-17 09:34
(5676,0,-262,20,-1,0,16,1,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,5676,0,0,0,0,'OLD Arcane Feedback','','','We were forced to learn some magics to protect us from what is commonly called our greatest enemy: the arcane.$B$BI would teach you a spell to help you defend yourself and your companions from those who would wield such power.','','','','','','',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13896,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0),
(5677,2,-262,20,-1,0,16,1,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,5676,0,0,0,0,'OLD Arcane Feedback','As much as I\'d like to show you our own special teachings of the Light, it is not our place. Your place is back in Stormwind with your own kind, $N... for now. Believe me, I mean no offense. When you return to High Priestess Laurena in the Cathedral of Light you\'ll understand what I\'m talking about--the time has come for your race to prepare you for the future; to separate yourself from others that follow a similar path.','Speak to High Priestess Laurena in Stormwind.','','','','','','','',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13896,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0),
(5678,2,-262,20,-1,0,16,1,0,0,0,0,0,0,0,0,0,0,8,0,0,0,0,5676,0,0,0,0,'OLD Arcane Feedback','It is time for you to return to Stormwind, young one. Your superiors there have called you back for more training. And although it disturbs me some, your race and mine are allies and I would not betray that.$B$BI do not mean to be so coy with you--my distrust of arcane magics, be they divine inspired or not, is still strong within me.$B$BYou will know of what I speak after you return to your Cathedral of Light. Speak to High Priestess Laurena when you arrive.','Speak to High Priestess Laurena in Stormwind.',NULL,NULL,'','','','','',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13896,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0),

thats 3 quests is for the priest quests BUT you learn not the spell he cast only the feedback spell on you so some is wornk with core or other

**Comment by Salja** [comment] 2014-11-18 11:29
well i looked now 2 days and i can say thats sucks hard no infos about the quest in TBC
the learn spells 19345 learn feedback by end quest is remove on TBC so you cant learn the spell by quest end

i have no more infos found but i think on tbc you dont learn by quest you can learn by trainer ?

**Comment by Salja** [comment] 2014-11-18 11:53
@Mibu86 as example the Feedback spell not learn by Garments quest.
the spell learn by quest Arcane Feedback you become from priest trainer at level 20 and on complete you become rank 1 of feedback rank 2 you become from trainer at level 30 and 40 50 60 70 etc.

problem on classic you have a spell "learn feedback" thats trigger the learn rank 1 spell feedback on tbc is the spell removed so wehn you complete the quest you not learn the spell only he buffed with it.

2 days of look i can say the core not support yet learn the right spell without trigger learn spell

and befor you ask of other projects NOTHING server in the www have fixed the quest yet =)

**Comment by Mibu86** [comment] 2014-11-18 12:34
WDDG(sandboxes) shit emulators and old mangos emulators under TBC had it fixed...somehow it got broken on the way.. it can be fixed

**Comment by Salja** [comment] 2014-11-18 12:41
i checked mangos old versions and not working only in classic is working

**Comment by Salja** [comment] 2014-11-18 12:41
the problem is not mangos the problem is the spell on classic the spell have effect learn on tbc the spell removed

**Comment by Mibu86** [comment] 2014-11-18 13:24
well ...  way not use .lua to solve the Problem? smth like "player completes Garments quest/ if class priest else if race# then learn rank 1 of spell ..." and add the missing ranks to trainer.... that should fix it without Core fix required.
But in order to do that u need to be able to be able to complete those Garments quests that requires that guard healed..

**Comment by Mibu86** [comment] 2014-11-18 13:25
I know you dont like Work.arounds but well then way not take advantage of the .lua system to fix if you put it there.

**Comment by Salja** [comment] 2014-11-18 14:33
Garments Quest works FINE the Garments Quest is NOT the Quest for the Spell FeedBack the Quest for Feedback is Quest 5676, 5677, 5678 Name Arcane Feedback the Garments Quest is NOT needed for FeedBack Quest.
Normal wehn its works you become with level 20 the FeedBack Quest from Trainer entry 376 Stormwind and after Complete you become the FeedBack Spell.
All other Ranks you become with level 30, 40, 50, 60, 70 from NPC Trainer

Only a Workround is add the spells rank 1 - 6 of Feedback to npc_trainer_template = entry 51

**Comment by Salja** [comment] 2014-11-24 13:52
@Mibu86 here a WORKROUND

SQL SCRIPT
insert into `npc_trainer_template` (`entry`, `spell`, `spellcost`, `reqskill`, `reqskillvalue`, `reqlevel`) values
('51','19271','500','0','0','30');
insert into `npc_trainer_template` (`entry`, `spell`, `spellcost`, `reqskill`, `reqskillvalue`, `reqlevel`) values
('51','19273','900','0','0','40');
insert into `npc_trainer_template` (`entry`, `spell`, `spellcost`, `reqskill`, `reqskillvalue`, `reqlevel`) values
('51','19274','1500','0','0','50');
insert into `npc_trainer_template` (`entry`, `spell`, `spellcost`, `reqskill`, `reqskillvalue`, `reqlevel`) values
('51','19275','2300','0','0','60');
insert into `npc_trainer_template` (`entry`, `spell`, `spellcost`, `reqskill`, `reqskillvalue`, `reqlevel`) values
('51','25441','6500','0','0','70');
UPDATE quest_template SET Title = 'Arcane Feedback' WHERE entry IN (5676, 5677, 5678);

insert into `creature_questrelation` (`id`, `quest`) values('376','5676');
insert into `creature_questrelation` (`id`, `quest`) values('11401','5678');
insert into `creature_questrelation` (`id`, `quest`) values('11406','5677');

insert into `creature_involvedrelation` (`id`, `quest`) values('376','5676');
insert into `creature_involvedrelation` (`id`, `quest`) values('376','5677');
insert into `creature_involvedrelation` (`id`, `quest`) values('376','5678');

LUA SCRIPT
local NpcId = 376
local QuestId_1 = 5676
local QuestId_2 = 5677
local QuestId_3 = 5678

local SPELL_FEEDBACK = 13896

local function PriestFeedbackOnQuestReward(event, player, creature, quest)
    if (quest:GetId() == QuestId_1) then
        player:LearnSpell(SPELL_FEEDBACK)
    elseif (quest:GetId() == QuestId_2) then
        player:LearnSpell(SPELL_FEEDBACK)
    elseif (quest:GetId() == QuestId_3) then
        player:LearnSpell(SPELL_FEEDBACK)
    end
end

RegisterCreatureEvent(NpcId, 34, PriestFeedbackOnQuestReward)

**Comment by Salja** [comment] 2014-11-29 17:56
@Mibu86 you test it ?

**Comment by Mibu86** [comment] 2014-11-29 19:15
make a .lua script and give me link.. pls..i queried the Sql script.

**Comment by Salja** [comment] 2014-11-29 19:17
it is a lua script copy in a file and save as .lua the other you insert in your sql
Lua Script http://pastebin.com/9actk95U
Sql Script http://pastebin.com/NjR3WD44

tested works fine for a workround

**Comment by Mibu86** [comment] 2014-11-29 20:39
Wut about The missing spell ranks from trainers?

**Comment by Salja** [comment] 2014-11-29 21:02
look in sql file have all and works

**Comment by Salja** [comment] 2014-11-29 21:02
on level 20 learn rank 1 from quest rank 2 = level 30 and and and from trainer

**Comment by Mibu86** [comment] 2014-11-29 21:22
kisses XD

**Closed as completed** 2014-11-29 22:18 UTC
Labels: OneServer, OneDatabase, OneScripts, MaNGOSOne
